# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tferreir <tferreir@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/05 15:13:43 by tiago_nevoa       #+#    #+#              #
#    Updated: 2022/03/16 20:52:02 by tferreir         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS			=	src/ft_flag_select.c src/ft_printf.c src/main.c \
					libft/ft_isprint.c libft/ft_putchar_fd.c libft/ft_putnbr_base.c libft/ft_putnbr_fd.c libft\ft_putstr_fd.c libft\ft_strlen.c ft_putunsigned_fd.c ft_puthex_fd.c

OBJS	= ${SRCS:.c=.o}
NAME	= libftprintf.a
HEAD	= includes
CC		= gcc
RM		= rm -f
CFLAGS	= -Wall -Wextra -Werror
AR		= ar rc
RANLIB	= ranlib

.c.o:
	${CC} ${CFLAGS} -c $< -o ${<:.c=.o} -I ${HEAD}

${NAME}: ${OBJS}
	${AR} ${NAME} ${OBJS}
	${RANLIB} ${NAME}

all: ${NAME}

clean:
	${RM} ${OBJS}

fclean: clean
	${RM} ${NAME}

re:	fclean all

.PHONY: all fclean clean re
