# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tiago_nevoa <tiago_nevoa@student.42.fr>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/05 15:13:43 by tiago_nevoa       #+#    #+#              #
#    Updated: 2022/03/05 16:43:34 by tiago_nevoa      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS			=	src/ft_printf.c \
					src/ft_flag_select.c \
					libft/ft_putchar_fd.c \
					libft/ft_putnbr_fd.c \
					libft/ft_putstr_fd.c \
					libft/ft_strlen.c

OBJS	= ${SRCS:.c=.o}
NAME	= libftprintf.a
HEAD	= includes
CC		= gcc
RM		= rm -f
CFLAGS	= -Wall -Wextra -Werror
AR		= ar rc
RANLIB	= ranlib

.c.o:
	${CC} ${CFLAGS} -c $< -o ${<:.c=.o} -I ${HEAD}

${NAME}: ${OBJS}
	${AR} ${NAME} ${OBJS}
	${RANLIB} ${NAME}
	cd libft && ${MAKE}
	cd ..
all: ${NAME}

clean:
	${RM} ${OBJS}
	cd libft && ${MAKE} clean
	cd ..

fclean: clean
	${RM} ${NAME}
	cd libft && ${MAKE} fclean
	cd ..

re:	fclean all
	cd libft && ${MAKE} re
	cd ..

.PHONY: all fclean clean re
	cd libft && ${MAKE} .PHONY
